@startuml
'Approved without any changes flow.
actor Reader
actor Editor
actor Reporter
participant UI
participant PublisherApi
participant ValidationApi
Reporter -> UI: Write article
Reporter -> UI: Submit for review
UI -> PublisherApi: Article(STATUS:NEW)
PublisherApi -> PublisherApi: Save Article(STATUS:OPEN_FOR_REVIEW)
PublisherApi -> ValidationApi: Validate Article Request(STATUS:IN_REVIEW_LEGAL)
ValidationApi -> ValidationApi: Validate
PublisherApi -> PublisherApi: Save Article(STATUS:IN_REVIEW_EDITOR)
Editor -> UI: Get Article(STATUS:IN_REVIEW_EDITOR)
UI -> PublisherApi: Get Article(STATUS:IN_REVIEW_EDITOR)
ValidationApi -> PublisherApi: Legal Recommendation
PublisherApi -> PublisherApi: Save Article(STATUS:REVIEWED_LEGAL)
Editor -> UI:View Article(STATUS:REVIEWED_LEGAL)
UI -> PublisherApi: Get Article(STATUS:REVIEWED_LEGAL)
Editor -> UI: Approve Article(STATUS:APPROVED)
UI -> PublisherApi: Approve Article(STATUS:APPROVED)
PublisherApi -> PublisherApi: Save Article(STATUS:PUBLISHED)
Reader -> UI: Read Published Article(STATUS:PUBLISHED)
UI -> PublisherApi: Get Article(STATUS:PUBLISHED)
PublisherApi -> UI: Article(STATUS:PUBLISHED)
@enduml
