apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: news-validation-api
spec:
  replicas: 3 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: news-validation-api
  template:
    metadata:
      labels:
        app: news-validation-api
    spec:
      containers:
        - name: mysql-news
          image: mysql:8-oracle
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              # The port that the container is running on in the cluster
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "my-secret-pw"
            - name: MYSQL_DATABASE
              value: "newsValidationDB"
            - name: MYSQL_USER
              value: "news-validation-api"
            - name: MYSQL_PASSWORD
              value: "NewsValidationApiPassword"
        - name: news-validation-api
          image: news-validation-api:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              # The port that the container is running on in the cluster